"""Добавил таблицу users

Revision ID: 7e1161e5aa0e
Revises: 
Create Date: 2026-01-21 09:16:51.785125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1161e5aa0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False, comment='Хеш пароля'),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('experience', sa.BigInteger(), server_default='0', nullable=False, comment='Время работы пользователя (по идее нужно подключать систему отслеживания сессий, чтобы в конце рабочего дня ему капал опыт'),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', 'SUPERVISOR', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
