"""добавил атрибут department в users

Revision ID: c21802ebd3d8
Revises: 7e1161e5aa0e
Create Date: 2026-01-22 12:12:42.265449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21802ebd3d8'
down_revision: Union[str, Sequence[str], None] = '7e1161e5aa0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(), comment='Отдел, где работает сотрудник'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
